// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-west-2:40b0d2bb-d05c-48d9-983a-6e163d5993a1';
var aws_cognito_region = 'us-west-2';
var aws_mobile_analytics_app_id = '095f2100c8aa45bebb8b8997bfd58a55';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '0ab16865-006a-42a7-b94c-751c65a3d0d2';
var aws_project_name = 'chuckjones';
var aws_project_region = 'us-west-2';
var aws_resource_name_prefix = 'chuckjones-mobilehub-434185951';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
